### PR TITLE
[Feature] Copy URI Ability

### PR DESCRIPTION
**Pull request by Joeasaurus**
Fixed blocking issue from previous PR #143.

### CODE REVIEW

**Comment by dirkgroenen** [comment]
Thanks, let me test this feature as soon as possible and merge it if everything works :+1:

**Comment by dirkgroenen** [comment]
I've just merged it in the v2.0 branch and is seems to work fine. Lemme merge it in master so it's available upon next release.

**Comment by Joeasaurus** [comment]
Cheers boss :smile:

**Comment by dirkgroenen** [comment]
It's there in the new version which I just uploaded. ;)

**Comment by Joeasaurus** [comment]
:smile:

**Pull request merged**
