### PR TITLE
Fix build

### LINKED ISSUE #83: Problem with cgPrompt in development
I'm trying to get the development environment up and running. 

- OS X 10.10, node/npm from brew.
- Ran the instructions in README to get up and running in development
- Had to choose Angular version during bower install (choose 1.3.15)
    - One of the choices was `angular#~1.2.16 which resolved to 1.2.28 and is required by angular-prompt#1.1.0`.
    - All other choices/requirements were for 1.3.x

At this point, `grunt watch` gets the server up and running but I get this error in the browser.

<pre>
Error: [$injector:modulerr] Failed to instantiate module mopify due to:
[$injector:modulerr] Failed to instantiate module mopify.music.playlists due to:
[$injector:modulerr] Failed to instantiate module cgPrompt due to:
[$injector:nomod] Module 'cgPrompt' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.15/$injector/nomod?p0=cgPrompt
minErr/<@http://localhost:8000/src/vendor/angular/angular.js:63:12
module/<@http://localhost:8000/src/vendor/angular/angular.js:1774:1
ensure@http://localhost:8000/src/vendor/angular/angular.js:1698:38
module@http://localhost:8000/src/vendor/angular/angular.js:1772:1
loadModules/<@http://localhost:8000/src/vendor/angular/angular.js:4115:22
forEach@http://localhost:8000/src/vendor/angular/angular.js:323:11
loadModules@http://localhost:8000/src/vendor/angular/angular.js:4099:5
loadModules/<@http://localhost:800
</pre>

I am unfamiliar with bower, sorry if this is a dumb question.

### PR DESCRIPTION
**Pull request by werkshy**
Add angular-prompt to build.config.js. Fixes #83

### CODE REVIEW

**Comment by dirkgroenen** [comment]
The ```build.config.js``` already contains the cgPrompt script which is located in the ```dist``` directory. ([Line 65](https://github.com/werkshy/mopidy-mopify/blob/35f79fcf4fd09db50e4ca37cd474c5c1f25211e6/build.config.js#L68))

**Comment by werkshy** [comment]
Not sure how I missed that. The problem then is that 'bower install' doesn't include the dist/ directory for angular-prompt (or the minified js.) Updated the PR to use the non-minified js.

**Comment by dirkgroenen** [comment]
I'm using a custom build of angular prompt, which should be included in the vendor directory. I noticed that angular prompt was also included in the bower.json file, which it shouldn't.

I've removed it from the bower.json file current development branch. Hopefully the fixes the problem. I'll leave this PR open until I've tested this.

**Comment by werkshy** [comment]
I see that angular-prompt is checked into 'development' but dist/angular-prompt.min.js is not:

https://github.com/dirkgroenen/mopidy-mopify/tree/development/src/vendor/angular-prompt

**Comment by dirkgroenen** [comment]
Oh I see. I need to take a better look at this. At the moment I'm doubting if I'm still using the custom build or the original version. 

If I'm using the custom version it would make sense that the minified version isn't included and the build file is incorrect.

**Pull request closed without merging**
